### PR TITLE
Python packaging changes, close #101

### LINKED ISSUE #101: Publish on PyPI
Hi @joan2937 - would you mind if I was to publish this on the Python Package Index so that it can be installed with pip?

If you want to do it yourself - please do - but if not, I'm happy to, and I'll try to keep it updated as you do releases.

Thanks

### PR DESCRIPTION
**Pull request by bennuttall**
Re: #101

### CODE REVIEW

**Comment by joan2937** [comment]
I pushed out a new version (V59) today.  That meant I had to revert the changes to setup.py.

**Comment by bennuttall** [comment]
Good to hear there's a new version out. Why did you have to revert the changes?

**Comment by joan2937** [comment]
When I built on a couple of Pis the Python builds failed and the module was not updated.  I'm afraid I didn't really investigate, I just assumed I had hit the same problem you had referred to.

I'll try the build again and make a note of the errors.

**Comment by joan2937** [comment]
I get this on a couple of Pis.

```
if which python2; then python2 setup.py install; fi
/usr/bin/python2
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    from setuptools import setup, find_packages
ImportError: No module named setuptools
Makefile:80: recipe for target 'install' failed
make: *** [install] Error 1
```
I guess the setuptools package isn't a standard Python install.

**Comment by joan2937** [comment]
@bennuttall 

Is there anything I can do (in the absence of setuptools) to make the current pigpio setup.py more pip friendly?

**Comment by bennuttall** [comment]
I made the following changes:

- Remove trailing slash from URL
- Update description "Raspberry gpio module" to "Raspberry Pi GPIO module"
- Added keywords
- Added classifiers

Not hugely important (not necessary for PyPI, I was just tidying up)

I also used `packages=find_packages()` which is why I changed the import line.

If you can manually cherry-pick the changes above that would be handy.

FYI I pushed it to PyPI but something broke and it doesn't import properly, then Christmas happened and I left it be. I'll get back to it soon.

Also, I wanted to check we're ok to upgrade the Raspbian packages? Is pigpio stable at the v59 release?

**Comment by joan2937** [comment]
Okay.

I'll use the following from now on.
```
#!/usr/bin/env python

from distutils.core import setup

setup(name='pigpio',
      version='1.35',
      author='joan',
      author_email='joan@abyz.co.uk',
      maintainer='joan',
      maintainer_email='joan@abyz.co.uk',
      url='http://abyz.co.uk/rpi/pigpio/python.html',
      description='Raspberry Pi GPIO module',
      long_description='Raspberry Pi Python module to access the pigpio daemon',
      download_url='http://abyz.co.uk/rpi/pigpio/pigpio.zip',
      license='unlicense.org',
      py_modules=['pigpio'],
      keywords=['raspberrypi', 'gpio',],
      classifiers=[
         "Programming Language :: Python :: 2",
         "Programming Language :: Python :: 3",
      ]
     )
```
I can't tell if V59 is more stable than V55.  I have no information either way.

**Comment by joan2937** [comment]
I have released V60 with the above change and a bugfix to 100% PWM (it was 99.976%).

**Comment by bennuttall** [comment]
Ok thanks. We're published on PyPI: https://pypi.python.org/pypi/pigpio

**Comment by bennuttall** [comment]
And I've requested an update of the pigpio packages in the Raspbian archive - we should see them appear next week.

**Pull request merged**
