### PR TITLE
Include <stddef.h> for `size_t`

### PR DESCRIPTION
**Pull request by notinaboat**
`pigpio.h` uses `size_t`, so it should include `<stddef.h>`.

https://www.gnu.org/software/libc/manual/html_node/Important-Data-Types.html

### CODE REVIEW

**Comment by guymcswain** [comment]
> pigpio.h uses size_t, so it should include <stddef.h>

Not so, unless I missed the part about pigpio declaring to be ISO C compliant.

> Data Type: size_t
... On systems using the GNU C Library, this will be unsigned int or unsigned long int.

**Comment by notinaboat** [comment]
As it stands, `pigpio.h` gets the definition of `size_t` by including `<pthread.h>` (this includes `<sched.h>` which then includes `<stddef.h>`).

I'm not sure that ISO C or not really matters, it's just that its better to include the header that defines the type being used rather than rely on it being indirectly defined by pthread.

(Context: i'm passing `pigpio.h` to a `libclang` based [wrapper generator](https://github.com/JuliaInterop/Clang.jl#c-bindings-generator) to generate Julia bindings. The clang environment includes standard C headers, but not OS headers (like pthread). I can work around this easily enough, but the patch in this PR just seems like the "right way").

If `stddef.h` is not included, `size_t` is undefined. e.g.

```bash
pi@raspberrypi:/tmp $ cat foo.c
size_t x = 3;
pi@raspberrypi:/tmp $ gcc -c foo.c
foo.c:1:1: error: unknown type name ‘size_t’
 size_t x = 3;
 ^~~~~~
foo.c:1:1: note: ‘size_t’ is defined in header ‘<stddef.h>’; did you forget to ‘#include <stddef.h>’?
```

**Comment by guymcswain** [comment]
Ok, that makes sense.  Thanks.

**Comment by guymcswain** [comment]
@notinaboat ,  I tried to edit this PR to merge it into the develop branch but it looks like that creates a ton of commits and I'm not sure why.  Can you make sure your fork is up to date then re-submit the PR against the develop branch?

**Comment by notinaboat** [comment]
Hi @guymcswain, maybe its easier for you to just paste `#include <stddef.h>` into `pigpio.h` in your branch and close this PR? I'm not sure why the other commits are showing up in this PR. Probably my fault for basing my branch on `master`.

**Comment by guymcswain** [comment]
Merged in v79

**Pull request closed without merging**
