### PR TITLE
improve pigs documentation

### PR DESCRIPTION
**Pull request by BryanCrotaz**
Added more detail for newbie users
Reordered commands to group SPI and PWM commands for clarity (there's more that can be done here but this is a start)

### CODE REVIEW

**Comment by BryanCrotaz** [comment]
Couldn't find any script to build the docs, so can't test my syntax

**Comment by joan2937** [comment]
Thanks @BryanCrotaz.

Unfortunately the file you changed is automatically generated from the documentation source.  The documentation source is not held on github.  I did give the relevant source in my response to the issue.  It is that source you will need to edit.

**Comment by BryanCrotaz** [comment]
Could you add it to the repo so I can submit a PR?

**Comment by joan2937** [comment]
I'm afraid I don't want to do that as I just think it would open a can of worms about all sorts of other supporting tools and texts I might then be asked to add to git.

**Comment by BryanCrotaz** [comment]
I don’t mind if your private tools stay private - we don’t need to be able to build piglike, but adding any doc source means we can assist you with documentation

**Comment by BryanCrotaz** [comment]
If not then you’ll just have to reverse engineer the PRs you get on pigs.1 etc which won’t be a fun job

**Comment by BryanCrotaz** [comment]
You did say that apart from pigs everything else is documented in the code, so isn’t this the only file that needs to be added?

**Comment by guymcswain** [comment]
@BryanCrotaz ,
Please re-submit your PR with the changes written against the pigs source located in:
`pigpio/DOC/src/defs/pigs.def`

> Couldn't find any script to build the docs, so can't test my syntax

Located here:  `pigpio/DOC/makedoc`

**Pull request closed without merging**
