### PR TITLE
Release v76

### PR DESCRIPTION
**Pull request by guymcswain**
New APIs:
* `gpioWaveCreatePad` (pigpio C I/F)
* `wave_create_and_pad` (Python module and pigpiod C I/F)
* `wvcap` (pigs)

Closes PR #329 and Issue #126

### CODE REVIEW

**Comment by guymcswain** [comment]
@joan2937 , are there any other updates that you would like to include in this release?  Some potential candidates for your consideration:
* PR #342 
* Issue #339
* PR #307
* PR #332

**Comment by joan2937** [comment]
I would leave them out of 76 but put them straight in to the next putative release.  They look like the sort of changes which will be okay as long as the existing tests pass.  I wouldn't stress about them either way because they should each be easy to revert if they cause a problem.

**Comment by guymcswain** [comment]
Good suggestion - I'll start a new draft release after 76 so we can begin to vet the changes.

Last question on v76 - After generating the docs I just committed all files.  Every time I ran `makedoc` another database file was created.  There are also files in `DOC/tmp`.  I'd like to generate an updated `.gitignore` file to remove any cruft from the directory but I know not what I'm doing.

**Comment by joan2937** [comment]
The DOC/tmp directory should be .gitignored.

All but the pigpio.sqlite file in DOC/dbase should be .gitignored.  The backups will be purged eventually (by bin/purge.sh).  They are probably no longer required as the sources are now in git.

DOC/MAN can be .gitignored (all files are auto generated).

DOC/HTLM/*.html can be .gitignored (files are auto generated).
```
DOC/tmp
DOC/dbase/pigpio.sqlite.*
DOC/MAN
DOC/HTML/*.html
```

**Pull request merged**
